llm_model:
    model_name: "nvidia/Llama3-ChatQA-2-8B"
    max_new_tokens: 512

embed_model:
    query_model_name: "jinaai/jina-embeddings-v3"
    chunk_model_name: "jinaai/jina-embeddings-v3"
    query_kwargs:
        default_task: 'retrieval.query'
    chunk_kwargs:
        default_task: 'retrieval.passage'

retriever:
    k_vector_search: 3
    k_text_search: 3

paths:
    dataset_w_articles: './data/articles.jsonl'
    ratings_db: './data/db/ratings.db'
    logs_db: './data/db/logs.db'
    vector_index: './data/db/vector_index'
    text_index: '.data/db/bm25_retriever'  # path to enable bm25 retriever
    cache_dir: './hfcache'

ragas:
    ragas_dataset: './data/ragas_dataset.jsonl'
    llm_evaluator: "google/gemma-2-9b-it"
